### ISSUE TITLE
Can Compass maps in OCS have zoom feature beyond "zoom to"

### ISSUE THREAD

**Issue by ldford** [Ecotrust/COMPASS#77]
Arty wondering if we can have the + and - zoom capability with the Compass maps loaded in OCS beyond just the "zoom to" feature. I'd like to let him know on Friday at our meeting.

**Comment by rhodges** [comment]
To my knowledge traditional web-map-style zooming works fine, but I don't know which OCS pages have compass links working right now to test it.

@dnseminara @ldford Do you have a link to show me an example of this behavior?

If the concern is that there's no +/- buttons on the page for people using tablets, we can add those.

**Comment by dnseminara** [comment]
http://ocs.ecotrust.org/strategy-habitat/aspen-woodlands/
