### ISSUE TITLE
Change text from "Marine Planner" to "ODFW Compass" on admin login

### ISSUE THREAD

**Issue by ldford** [Ecotrust/COMPASS#92]
On log in pop-up, can we change the text to ODFW Compass?

http://compass.dfw.state.or.us/admin/

![image](https://cloud.githubusercontent.com/assets/6453589/14216591/8d6030fe-f7fe-11e5-93a1-0563b4c8235e.png)

**Comment by rhodges** [comment]
Compete: 0359bae1549817d4bc24abfbfc9be25237d618e1
