### ISSUE TITLE
Compass styles messed on on Chrome browser

### ISSUE THREAD

**Issue by ldford** [Ecotrust/COMPASS#94]
Below is screenshot of Compass on Chrome. Firefox and IE both seem to be fine.
![image](https://cloud.githubusercontent.com/assets/6453589/14800961/7fb01118-0afa-11e6-8ae8-33a50eda5149.png)

**Comment by rhodges** [comment]
@ldford I develop on Chrome (technically Chromium, but same thing) and am not seeing this.
Please try the following:
 - refresh
 - If still ugly, press ctrl + shift + 'R'
Let me know if either of those do the trick.

**Comment by ldford** [comment]
No luck. Tried those already. This is my version current version of Chrome: Version 50.0.2661.75 m (64-bit). Running an update, then will try again

**Comment by ldford** [comment]
Update fixed it.

**Comment by rhodges** [comment]
Awesome! I'm still on 49.0 - I will double check to see what an update does to me.

**Comment by ldford** [comment]
My versions:
Pre update: Version 50.0.2661**.75** m (64-bit)
Post update: Version 50.0.2661**.87** m (64-bit)
